# Generated by Django 5.2.1 on 2025-05-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('users', 'Обычный пользователь')], default='user', max_length=10),
        ),
    ]
